[package]
name = "rust-untitled"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = { version = "0.9.0-alpha.2" }
http = "1.1.0"
serde_json = "1.0.125"
reqwest = "0.12.7"
tokio = { version = "1.39.3", features = ["full"] }